### PR TITLE
Add support for 'chunked' Transfer-Encoding.

### PR DESCRIPTION
**Pull request by smira**

### CODE REVIEW

**Comment by izrik** [comment]
@smira Hi! Thanks for your contribution. I'll a little busy right now, but I'll try to check this PR as soon as possible. Do you have any tests that you were using to develop this? and could they be added to the [test_deproxy.py](https://github.com/izrik/pydeproxy/blob/master/test_deproxy.py) test script?

**Comment by smira** [comment]
@izrik I've included simple test on chunked encoding, not sure if it is fully correct

**Comment by izrik** [comment]
@smira Sorry it took so long. Thanks for the contribution! I'll cut a release today.

**Comment by izrik** [comment]
Done: https://pypi.python.org/pypi/deproxy/0.9

**Pull request merged**
